# Generated by Django 6.1.1 on 2026-10-03 08:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('kind', models.CharField(choices=[('signed_in', 'Signed in'), ('wrong_password', 'Wrong email or password'), ('wrong_code', 'Wrong code'), ('paused', 'Signing in paused for an hour'), ('passkey_added', 'Passkey added'), ('passkey_removed', 'Passkey removed'), ('authenticator_set_up', 'Authenticator app set up'), ('authenticator_removed', 'Authenticator app removed'), ('recovery_codes_issued', 'New recovery codes'), ('password_changed', 'Password changed'), ('signed_out_elsewhere', 'Signed out everywhere else'), ('reset_on_server', 'Reset on the server')], max_length=32)),
                ('detail', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=64)),
                ('device', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'verbose_name_plural': 'security log entries',
                'ordering': ['-at', '-pk'],
            },
        ),
    ]
