# Generated by Django 6.1.1 on 2026-10-03 13:21

import django.db.models.functions.text
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('asset', 'Asset account'), ('liability', 'Liability'), ('expense', 'Expense account'), ('income', 'Income account')], max_length=16)),
                ('kind', models.CharField(blank=True, choices=[('bank', 'Bank'), ('savings', 'Savings'), ('cash', 'Cash'), ('investment', 'Investment'), ('lent', 'Lent'), ('property', 'Property')], max_length=16)),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('opening_balance', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=24)),
                ('opened_on', models.DateField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('type'), name='account_name_unique_per_type')],
            },
        ),
    ]
