# Generated by Django 6.1.1 on 2026-10-03 15:09

from django.db import migrations, models


def rename(old, new):
    def run(apps, schema_editor):
        apps.get_model("masters", "Account").objects.filter(kind=old).update(kind=new)

    return run


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='kind',
            field=models.CharField(blank=True, choices=[('bank', 'Bank'), ('deposit', 'Deposit'), ('cash', 'Cash'), ('investment', 'Investment'), ('lent', 'Lent'), ('property', 'Property')], max_length=16),
        ),
        migrations.RunPython(rename("savings", "deposit"), rename("deposit", "savings")),
    ]
