# Generated by Django 6.1.1 on 2026-10-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_savings_to_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='kind',
            field=models.CharField(blank=True, choices=[('bank', 'Bank'), ('deposit', 'Deposit'), ('cash', 'Cash'), ('investment', 'Investment'), ('lent', 'Lent'), ('property', 'Property'), ('credit_card', 'Credit card'), ('loan', 'Loan'), ('mortgage', 'Mortgage'), ('debt', 'Debt')], max_length=16),
        ),
    ]
