# Generated by Django 6.1.1 on 2026-10-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_liability_kinds'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
