# Generated by Django 6.1.1 on 2026-10-03 17:07

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_closing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(choices=[('forest', 'Forest'), ('sage', 'Sage'), ('teal', 'Teal'), ('sky', 'Sky'), ('indigo', 'Indigo'), ('plum', 'Plum'), ('rose', 'Rose'), ('rust', 'Rust'), ('ochre', 'Ochre'), ('olive', 'Olive'), ('earth', 'Earth'), ('stone', 'Stone')], max_length=16)),
                ('icon', models.CharField(blank=True, choices=[('shopping-cart', 'Shopping cart'), ('shopping-bag', 'Shopping bag'), ('utensils', 'Cutlery'), ('coffee', 'Coffee'), ('house', 'House'), ('sofa', 'Sofa'), ('wrench', 'Wrench'), ('zap', 'Electricity'), ('droplet', 'Water'), ('flame', 'Flame'), ('wifi', 'Wi-Fi'), ('smartphone', 'Phone'), ('tv', 'TV'), ('car', 'Car'), ('fuel', 'Fuel'), ('bus', 'Bus'), ('train-front', 'Train'), ('bike', 'Bicycle'), ('plane', 'Plane'), ('tree-palm', 'Holiday'), ('heart-pulse', 'Health'), ('pill', 'Medicine'), ('dumbbell', 'Fitness'), ('scissors', 'Grooming'), ('shirt', 'Clothes'), ('graduation-cap', 'Education'), ('book-open', 'Books'), ('baby', 'Children'), ('paw-print', 'Pets'), ('gift', 'Gift'), ('hand-heart', 'Charity'), ('film', 'Film'), ('music', 'Music'), ('gamepad-2', 'Games'), ('party-popper', 'Celebration'), ('shield', 'Insurance'), ('receipt', 'Bills'), ('landmark', 'Tax'), ('briefcase', 'Work'), ('laptop', 'Laptop'), ('banknote', 'Cash'), ('coins', 'Coins'), ('percent', 'Interest'), ('trending-up', 'Returns'), ('package', 'Parcel')], max_length=32)),
                ('closed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='category_name_unique')],
            },
        ),
    ]
