# Generated by Django 6.1.1 on 2026-10-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(default='INR', max_length=3)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('pk', 1)), name='one_setting_row')],
            },
        ),
    ]
