# Generated by Django 6.1.1 on 2026-10-03 14:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('action', models.CharField(choices=[('created', 'Created'), ('edited', 'Edited'), ('base_currency_changed', 'Base currency changed')], max_length=32)),
                ('subject_id', models.PositiveBigIntegerField()),
                ('subject_type', models.CharField(max_length=32)),
                ('subject_name', models.CharField(max_length=100)),
                ('changes', models.JSONField(blank=True, default=list)),
                ('subject_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name_plural': 'history entries',
                'ordering': ['-at', '-pk'],
                'indexes': [models.Index(fields=['subject_model', 'subject_id'], name='core_histor_subject_6d7523_idx')],
            },
        ),
    ]
