# Generated by Django 6.1.1 on 2026-10-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyentry',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('edited', 'Edited'), ('closed', 'Closed'), ('reopened', 'Reopened'), ('deleted', 'Deleted'), ('base_currency_changed', 'Base currency changed')], max_length=32),
        ),
    ]
