# Generated by Django 6.1.1 on 2026-10-05 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_closing'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='time_zone',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='historyentry',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('edited', 'Edited'), ('closed', 'Closed'), ('reopened', 'Reopened'), ('deleted', 'Deleted'), ('base_currency_changed', 'Base currency changed'), ('time_zone_changed', 'Time zone changed')], max_length=32),
        ),
    ]
