#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — Cloudflare R2 media bucket for Kosha.
# See docs/adr/0001-media-in-a-private-r2-bucket.md.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5
R2_DASHBOARD="https://dash.cloudflare.com/?to=/:account/r2/overview"

# Runs the round-trip check with the project's own boto3: through uv in a
# checkout, or through the published image on a server that only has Docker.
verify_bucket() {
  local check
  check=$(cat <<'PY'
import os
import sys
import urllib.error
import urllib.request
import uuid

import boto3
from botocore.config import Config
from botocore.exceptions import BotoCoreError, ClientError

endpoint = os.environ["S3_ENDPOINT_URL"]
bucket = os.environ["S3_BUCKET_NAME"]
s3 = boto3.client(
    "s3",
    endpoint_url=endpoint,
    aws_access_key_id=os.environ["S3_ACCESS_KEY_ID"],
    aws_secret_access_key=os.environ["S3_SECRET_ACCESS_KEY"],
    region_name="auto",
    config=Config(signature_version="s3v4"),
)
key = f"kosha-setup-check-{uuid.uuid4().hex}.txt"
body = b"kosha r2 setup check"

try:
    s3.put_object(Bucket=bucket, Key=key, Body=body)
except (BotoCoreError, ClientError) as exc:
    sys.exit(f"upload failed: {exc}")
print("  ok: uploaded a test file")

try:
    url = s3.generate_presigned_url(
        "get_object", Params={"Bucket": bucket, "Key": key}, ExpiresIn=60
    )
    if urllib.request.urlopen(url, timeout=15).read() != body:
        sys.exit("signed URL returned the wrong content")
    print("  ok: read it back through a signed URL")

    try:
        urllib.request.urlopen(f"{endpoint}/{bucket}/{key}", timeout=15)
        sys.exit("the file is readable WITHOUT a signature: the bucket is not private")
    except urllib.error.HTTPError as exc:
        print(f"  ok: unsigned request refused ({exc.code})")
finally:
    s3.delete_object(Bucket=bucket, Key=key)
    print("  ok: deleted the test file")
PY
)
  export S3_BUCKET_NAME S3_ENDPOINT_URL S3_ACCESS_KEY_ID S3_SECRET_ACCESS_KEY
  if command -v uv >/dev/null 2>&1 && [[ -f pyproject.toml ]]; then
    uv run python -c "$check"
  elif command -v docker >/dev/null 2>&1; then
    docker run --rm -e S3_BUCKET_NAME -e S3_ENDPOINT_URL -e S3_ACCESS_KEY_ID \
      -e S3_SECRET_ACCESS_KEY "ghcr.io/prabhuakshay/kosha:${KOSHA_VERSION:-latest}" \
      python -c "$check"
  else
    warn "neither uv (in a Kosha checkout) nor Docker is available to run the check"
    return 1
  fi
}

banner "Cloudflare R2 media bucket for Kosha"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Which deployment is this for?"
say "Each deployment gets its own bucket and its own token, so a leaked dev"
say "key can never touch production files."
printf '\n'
printf '  %sd%s  development: writes to this checkout'"'"'s .env\n' "$BOLD" "$RESET"
printf '  %sp%s  production:  writes to the .env next to compose.prod.yaml\n\n' "$BOLD" "$RESET"
TARGET=""
while [[ "$TARGET" != "d" && "$TARGET" != "p" ]]; do
  printf '  %sDevelopment or production? [d/p]%s ' "$BOLD" "$RESET"
  read -r TARGET || true
done

if [[ "$TARGET" == "d" ]]; then
  SUGGESTED_BUCKET="kosha-media-dev"
  TOKEN_NAME="kosha-dev"
  RESTART_HINT="docker compose up -d"
else
  SUGGESTED_BUCKET="kosha-media"
  TOKEN_NAME="kosha-production"
  RESTART_HINT="docker compose -f compose.prod.yaml up -d"
fi

printf '  %sEnv file to write%s %s[Enter for %s]%s ' "$BOLD" "$RESET" "$DIM" "$ENV_FILE" "$RESET"
read -r chosen_env || true
ENV_FILE="${chosen_env:-$ENV_FILE}"
note "values will be written to $ENV_FILE"

if [[ "$TARGET" == "d" ]]; then
  printf '\n'
  warn "With S3_BUCKET_NAME set, your dev stack stores uploads in this bucket"
  warn "instead of media/. Remove the S3_* lines from $ENV_FILE to switch back."
fi
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Open R2 in the Cloudflare dashboard"
open_url "$R2_DASHBOARD"
step "Sign in, and pick your account if you have more than one."
step "If R2 asks you to subscribe or add a payment method, do it."
note "R2 has a free tier; setting it up once covers every bucket."
pause "Press Enter when you can see the R2 Overview page"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Create a private bucket"
say "Choose the bucket name first; you'll type the same name in the dashboard."
note "lowercase letters, digits and hyphens, 3-63 characters, no hyphen at the ends"
while true; do
  ask S3_BUCKET_NAME "Bucket name [Enter for $SUGGESTED_BUCKET]:"
  S3_BUCKET_NAME="${S3_BUCKET_NAME:-$SUGGESTED_BUCKET}"
  [[ "$S3_BUCKET_NAME" =~ ^[a-z0-9][a-z0-9-]{1,61}[a-z0-9]$ ]] && break
  warn "'$S3_BUCKET_NAME' isn't a valid R2 bucket name"
  S3_BUCKET_NAME=""
done
printf '\n'
step "On the R2 Overview page, click Create bucket."
step "Name it exactly: ${BOLD}${S3_BUCKET_NAME}${RESET}"
step "Location: leave it on None unless you need a jurisdiction (e.g. EU)."
note "A jurisdiction can't be changed later, and it changes the endpoint URL."
step "Create the bucket."
warn "Do NOT enable the Public Development URL or connect a custom domain."
warn "Kosha only ever serves these files through short-lived signed URLs."
pause "Press Enter once the bucket exists"
write_env S3_BUCKET_NAME "$S3_BUCKET_NAME"
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Create an API token for this bucket only"
open_url "$R2_DASHBOARD"
step "Click Manage API tokens."
step "Click Create Account API token."
note "An account token keeps working if your Cloudflare user is ever removed."
step "Token name: ${BOLD}${TOKEN_NAME}${RESET}"
step "Permissions: Object Read & Write."
step "Specify bucket(s): Apply to specific buckets only, then pick ${BOLD}${S3_BUCKET_NAME}${RESET}."
step "Leave TTL on Forever (or set an expiry and rerun this wizard before it lapses)."
step "Create the token."
warn "The Secret Access Key is shown only once. Keep the page open until it's pasted."
printf '\n'
ask S3_ACCESS_KEY_ID "Paste the Access Key ID:"
ask_secret S3_SECRET_ACCESS_KEY "Paste the Secret Access Key (hidden):"
say "The same page lists the S3 endpoint for S3 clients."
note "https://<ACCOUNT_ID>.r2.cloudflarestorage.com, or https://<ACCOUNT_ID>.eu.r2... for EU"
while true; do
  ask S3_ENDPOINT_URL "Paste the endpoint URL:"
  # Some views show the endpoint with the bucket appended; Kosha wants it bare.
  S3_ENDPOINT_URL="${S3_ENDPOINT_URL%/}"
  S3_ENDPOINT_URL="${S3_ENDPOINT_URL%/"$S3_BUCKET_NAME"}"
  [[ "$S3_ENDPOINT_URL" =~ ^https://[a-f0-9]+(\.[a-z]+)?\.r2\.cloudflarestorage\.com$ ]] && break
  warn "that doesn't look like an R2 endpoint; expected https://<ACCOUNT_ID>.r2.cloudflarestorage.com"
done
write_env S3_ACCESS_KEY_ID "$S3_ACCESS_KEY_ID"
write_env S3_SECRET_ACCESS_KEY "$S3_SECRET_ACCESS_KEY"
write_env S3_ENDPOINT_URL "$S3_ENDPOINT_URL"
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Check the bucket works and is private"
say "Uploads a small test file, reads it back through a signed URL, checks an"
say "unsigned request is refused, then deletes it."
printf '\n'
if verify_bucket; then
  printf '\n  %s✓ R2 is ready for Kosha%s\n' "$GREEN" "$RESET"
else
  printf '\n'
  warn "The check failed. Fix the bucket or token in the dashboard and rerun"
  warn "this wizard; Enter keeps every value already saved."
  SKIPPED+=("a passing R2 check (rerun scripts/setup-r2.sh)")
fi
pause

finish
note "Apply the new settings: $RESTART_HINT"
printf '\n'
